services:
  db:
    image: postgres:17
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_trap_db
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
